project:
  type: website

website:
  title: "OmniVault"
  site-url: https://ricman1029.github.io/OmniVault/
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Apuntes"
        href: apuntes/index.qmd
      - text: "Proyectos"
        href: proyectos/index.qmd
